---
framework: mocha
preRun:
     command:
        - npm install
        - npm install -g chai
        - npm run prepare
preMerge:
  pattern:
    - "test/scripts/extend/*.js"
postMerge:
  pattern: 
    - "test/scripts/extend/*.js"
postRun:
     command:
        - node --version
configFile: ".mocharc.yml"
version: 1.3
